name: Publish to Registry
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: democraciaenred/debatamos
          tag: latest
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_BUILD_USER }}
          password: ${{ secrets.DOCKER_BUILD_PASSWORD }}
